[features]
seeds = false
skip-lint = false
[programs.localnet]
gm_anchor = "BTM5fZcVGeTgZ8skRPsFm5hWQCRhaaQNub7TEedz8pfZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/savvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
